# Generated by Django 4.2 on 2023-11-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakebox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
