# Generated by Django 4.2.5 on 2023-11-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakebox', '0003_rename_category_cakes_category_alter_cakes_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='cakevarient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakebox.cakevarients'),
        ),
    ]
